name: PlayerPingPlugin
version: '${project.version}'
main: dev.manere.playerping.PlayerPingPlugin
authors: [Manere_]
description: Simple /ping [player] command using my Command API.
website: https://github.com/Manered/PlayerPing
commands:
  ping:
    permission: ping.command

permissions:
  ping.command:
    default: true