name: PlayerPingPlugin
version: '${project.version}'
main: dev.manere.playerping.PlayerPingPlugin
api-version: 1.19
authors: [Manere_]
description: Simple /ping [player] command using my Command API.
website: https://github.com/Manered/PlayerPing
commands:
  ping:
